### ISSUE TITLE
[1.21] CursedEarthReturns's Minecraft tags are not read by the game

### ISSUE THREAD

**Issue by TelepathicGrunt** [nanonestor/CursedEarthReturns#2]
In 1.21, Minecraft changed `blocks` and `items` tags to be just `block` and `item`.
![image](https://github.com/user-attachments/assets/40f4bf87-ea0c-4eeb-b3b4-6a170aee50a1)

This means CursedEarthReturns's tags are not being read by the game right now as they are still plural.
https://github.com/nanonestor/CursedEarthReturns/tree/1.21-neoforge/src/main/resources/data/minecraft/tags

Causes the Blessed Flower to not have the small flower tags

**Comment by nanonestor** [comment]
Fixed with version 1.6 just published.  :)  For both 1.21.1 and now 1.21.3.
